baseURL = "https://yaf.github.io/journal-d-un-formateur-en-2015/"
languageCode = "fr-FR"
title = "Journal d'un formateur en 2015"
theme = "journal-formateur-2015"
DefaultContentLanguage = "fr"
disableKinds = ["sitemap"]

